# Note: Do not change these following values to match with your environment.
# Create a new `config.override.yaml` to merge the config instead.

app:
  env: local # E.g. local, staging, production.

http:
  port: 8080

database:
  dsn: root:@tcp(127.0.0.1:3306)/example?charset=utf8mb4&parseTime=True&loc=Local
