// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	handler "github.com/irvingdinh/example-go/internal/http/handler"
	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// TaskHandler provides a mock function with given fields:
func (_m *Handler) TaskHandler() handler.TaskHandler {
	ret := _m.Called()

	var r0 handler.TaskHandler
	if rf, ok := ret.Get(0).(func() handler.TaskHandler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(handler.TaskHandler)
		}
	}

	return r0
}
