// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// TaskHandler is an autogenerated mock type for the TaskHandler type
type TaskHandler struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: c
func (_m *TaskHandler) CreateTask(c *gin.Context) {
	_m.Called(c)
}

// DeleteTask provides a mock function with given fields: c
func (_m *TaskHandler) DeleteTask(c *gin.Context) {
	_m.Called(c)
}

// GetTasks provides a mock function with given fields: c
func (_m *TaskHandler) GetTasks(c *gin.Context) {
	_m.Called(c)
}

// MarkTaskAsCompleted provides a mock function with given fields: c
func (_m *TaskHandler) MarkTaskAsCompleted(c *gin.Context) {
	_m.Called(c)
}
